language: go
go:
- tip
before_install:
- openssl aes-256-cbc -K $encrypted_982672662e13_key -iv $encrypted_982672662e13_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
addons:
  ssh_known_hosts: 68.168.138.112
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@68.168.138.112 -p 27402 -o StrictHostKeyChecking=no 'cd /home/travis/testtravis && git pull && /usr/local/go/bin/go build main.go'
